services:
  maria-db:
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql
      - ./initscripts:/docker-entrypoint-initdb.d
      - ./initscripts/exercises:/var/lib/mysql-files/exercises
    container_name: maria-db
    restart: unless-stopped
    tty: true
    ports:
      - 3308:3306
    environment:
      MARIADB_ROOT_PASSWORD: pass1234
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      provedb:
        ipv4_address: 10.10.0.2

  redis:
    build:
      context: .
      dockerfile: dockerfiles/redis.dockerfile
    volumes:
      - ./redis/data:/data
      - ./logs/redis:/var/log/redis
    container_name: redis-cache
    restart: unless-stopped
    command: redis-server --requirepass redis1234
    ports:
      - "6379:6379"
    networks:
      provedb:
        ipv4_address: 10.10.0.3
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis1234", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    build:
      context: .
      dockerfile: dockerfiles/rabbitmq.dockerfile
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./logs/rabbitmq:/var/log/rabbitmq
    container_name: rabbitmq-service
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672   # AMQP protocol
      - 15672:15672 # Management interface
    networks:
      provedb:
        ipv4_address: 10.10.0.4
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 10
image_processing-app:
    build:
      context: .
      dockerfile: dockerfiles/image_processing.dockerfile
    volumes:
      - ./local_sources/image_processing-app:/app
      - ./built_services/image_processing-app:/app/dist
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_TTL=${REDIS_TTL}
      - REDIS_DB=${REDIS_DB}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=${RABBITMQ_VHOST}
      - RABBITMQ_QUEUE=${RABBITMQ_QUEUE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    networks:
      provedb:
        ipv4_address: 10.10.0.5
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

networks:
  provedb:
    driver: bridge
    ipam: 
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1