services:
  maria-db:
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql
      - ./initscripts:/docker-entrypoint-initdb.d
      - ./exercises:/var/lib/mysql-files/exercises
    container_name: maria-db
    restart: unless-stopped
    tty: true
    ports:
      - 3308:3306
    environment:
      MARIADB_ROOT_PASSWORD: pass1234
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      provedb:
        ipv4_address: 10.10.0.2

networks:
  provedb:
    driver: bridge
    ipam: 
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1

