# rabbitmq.conf
default_user = guest
default_pass = guest
default_vhost = /

management.listener.port = 15672
management.listener.ssl = false

# Memory threshold at which the flow control is triggered
vm_memory_high_watermark.relative = 0.8

# Disk free space limit
disk_free_limit.absolute = 2GB

# Maximum number of connections
connection_max = 1000

# Default number of channels per connection
channel_max = 150

# Heartbeat timeout
heartbeat = 60